name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -f package-lock.json
          npm install --no-audit --no-fund
          npm install -D tailwindcss@latest postcss@latest autoprefixer@latest --no-audit --no-fund
          
      - name: Create Tailwind config
        run: |
          echo 'module.exports = {
            content: [
              "./app/**/*.{js,ts,jsx,tsx,mdx}",
              "./pages/**/*.{js,ts,jsx,tsx,mdx}",
              "./components/**/*.{js,ts,jsx,tsx,mdx}",
            ],
            theme: {
              extend: {},
            },
            plugins: [],
          }' > tailwind.config.js
          
          echo 'module.exports = {
            plugins: {
              tailwindcss: {},
              autoprefixer: {},
            },
          }' > postcss.config.js
          
      - name: Build
        run: |
          echo "Starting build..."
          npm run build
          echo "Build completed"
          echo "Checking out directory:"
          ls -la out/
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production
          CI: false
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 